server:
  port: 8001
  servlet:
    context-path: /user-service

spring:
  application:
    name: user-service
  cloud:
    nacos:
      server-addr: 119.91.73.146:8848
      discovery:
        username: nacos
        password: PublicCode2001!
        namespace: public
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://119.91.73.146/awesome?useUnicode=true&characterEncoding=utf8&useAffectedRows=true
    username: root
    password: PublicCode2001!
    redis:
      port: 6379
      password: PublicCode2001!

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
