server:
  port: 8004
  servlet:
    context-path: /forum-service

spring:
  application:
    name: forum-service
  cloud:
    nacos:
      server-addr: 119.91.73.146:8848
      discovery:
        username: nacos
        password: PublicCode2001!
        namespace: public

