server:
  port: 8004
  servlet:
    context-path: /forum-service

spring:
  application:
    name: forum-service
  cloud:
    nacos:
      server-addr: 119.91.73.146:8848
      discovery:
        username: nacos
        password: PublicCode2001!
        namespace: public
        ip: 8.135.61.132
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://119.91.73.146/awesome?useUnicode=true&characterEncoding=utf8
    username: root
    password: PublicCode2001!
  redis:
    host: 119.91.73.146
    port: 6379
    password: PublicCode2001!

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

rocketmq:
  name-server: 119.91.73.146:9876
  producer:
    group: forum_producer_group